### ISSUE TITLE
Downloaded music does not play on cellular data

### ISSUE THREAD

**Issue by mr-f0xx** [AppleBetas/Melody#29]
It needs a Wifi connection to play music even if it's already in my iphone library
And no playing view when i play a track..

**Comment by AppleBetas** [comment]
Now playing view is intentionally left out.

**Comment by AppleBetas** [comment]
Cannot reproduce.

**Comment by AppleBetas** [comment]
Was able to reproduce. Fixing soon.

**Comment by AppleBetas** [comment]
Fixed in c032c7f
